//Do not edit! This file was generated by Unity-ROS MessageGeneration.

using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RoboteqDiff
{
    [Serializable]
    public class AuxDataMsg : Message
    {
        public const string k_RosMessageName = "roboteq_diff_msgs/AuxData";
        public override string RosMessageName => k_RosMessageName;

        public float v_bat;
        public float bc_i_bat;
        public float bc_i_mot1;
        public float bc_i_mot2;
        public float bc_temp_mcu;
        public float fc_i_bat;
        public float fc_i_mot1;
        public float fc_i_mot2;
        public float fc_temp_mcu;
        public float rc_i_bat;
        public float rc_i_mot1;
        public float rc_i_mot2;
        public float rc_temp_mcu;

        public AuxDataMsg()
        {
            v_bat = 0.0f;
            bc_i_bat = 0.0f;
            bc_i_mot1 = 0.0f;
            bc_i_mot2 = 0.0f;
            bc_temp_mcu = 0.0f;
            fc_i_bat = 0.0f;
            fc_i_mot1 = 0.0f;
            fc_i_mot2 = 0.0f;
            fc_temp_mcu = 0.0f;
            rc_i_bat = 0.0f;
            rc_i_mot1 = 0.0f;
            rc_i_mot2 = 0.0f;
            rc_temp_mcu = 0.0f;
        }

        public AuxDataMsg(float v_bat, float bc_i_bat, float bc_i_mot1, float bc_i_mot2, float bc_temp_mcu,
            float fc_i_bat, float fc_i_mot1, float fc_i_mot2, float fc_temp_mcu, float rc_i_bat, float rc_i_mot1,
            float rc_i_mot2, float rc_temp_mcu)
        {
            this.v_bat = v_bat;
            this.bc_i_bat = bc_i_bat;
            this.bc_i_mot1 = bc_i_mot1;
            this.bc_i_mot2 = bc_i_mot2;
            this.bc_temp_mcu = bc_temp_mcu;
            this.fc_i_bat = fc_i_bat;
            this.fc_i_mot1 = fc_i_mot1;
            this.fc_i_mot2 = fc_i_mot2;
            this.fc_temp_mcu = fc_temp_mcu;
            this.rc_i_bat = rc_i_bat;
            this.rc_i_mot1 = rc_i_mot1;
            this.rc_i_mot2 = rc_i_mot2;
            this.rc_temp_mcu = rc_temp_mcu;
        }

        public static AuxDataMsg Deserialize(MessageDeserializer deserializer)
        {
            return new AuxDataMsg(deserializer);
        }

        private AuxDataMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out v_bat);
            deserializer.Read(out bc_i_bat);
            deserializer.Read(out bc_i_mot1);
            deserializer.Read(out bc_i_mot2);
            deserializer.Read(out bc_temp_mcu);
            deserializer.Read(out fc_i_bat);
            deserializer.Read(out fc_i_mot1);
            deserializer.Read(out fc_i_mot2);
            deserializer.Read(out fc_temp_mcu);
            deserializer.Read(out rc_i_bat);
            deserializer.Read(out rc_i_mot1);
            deserializer.Read(out rc_i_mot2);
            deserializer.Read(out rc_temp_mcu);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(v_bat);
            serializer.Write(bc_i_bat);
            serializer.Write(bc_i_mot1);
            serializer.Write(bc_i_mot2);
            serializer.Write(bc_temp_mcu);
            serializer.Write(fc_i_bat);
            serializer.Write(fc_i_mot1);
            serializer.Write(fc_i_mot2);
            serializer.Write(fc_temp_mcu);
            serializer.Write(rc_i_bat);
            serializer.Write(rc_i_mot1);
            serializer.Write(rc_i_mot2);
            serializer.Write(rc_temp_mcu);
        }

        public override string ToString()
        {
            return "AuxDataMsg: " +
                   "\nv_bat: " + v_bat.ToString() +
                   "\nbc_i_bat: " + bc_i_bat.ToString() +
                   "\nbc_i_mot1: " + bc_i_mot1.ToString() +
                   "\nbc_i_mot2: " + bc_i_mot2.ToString() +
                   "\nbc_temp_mcu: " + bc_temp_mcu.ToString() +
                   "\nfc_i_bat: " + fc_i_bat.ToString() +
                   "\nfc_i_mot1: " + fc_i_mot1.ToString() +
                   "\nfc_i_mot2: " + fc_i_mot2.ToString() +
                   "\nfc_temp_mcu: " + fc_temp_mcu.ToString() +
                   "\nrc_i_bat: " + rc_i_bat.ToString() +
                   "\nrc_i_mot1: " + rc_i_mot1.ToString() +
                   "\nrc_i_mot2: " + rc_i_mot2.ToString() +
                   "\nrc_temp_mcu: " + rc_temp_mcu.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}