//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RoboteqDiff
{
    [Serializable]
    public class ControlDataMsg : Message
    {
        public const string k_RosMessageName = "roboteq_diff_msgs/ControlData";
        public override string RosMessageName => k_RosMessageName;

        public double linear_distance;
        public double angular_distance;
        public double dt;
        public double inductive_prox_left_filtered;
        public double inductive_prox_right_filtered;
        public bool ir_aluminum_lf;
        public bool ir_aluminum_rf;
        public bool ir_aluminum_lr;
        public bool ir_aluminum_rr;
        public bool ir_retro_left;
        public bool ir_retro_right;
        public bool chrg_hall;
        public float v_bat;

        public ControlDataMsg()
        {
            this.linear_distance = 0.0;
            this.angular_distance = 0.0;
            this.dt = 0.0;
            this.inductive_prox_left_filtered = 0.0;
            this.inductive_prox_right_filtered = 0.0;
            this.ir_aluminum_lf = false;
            this.ir_aluminum_rf = false;
            this.ir_aluminum_lr = false;
            this.ir_aluminum_rr = false;
            this.ir_retro_left = false;
            this.ir_retro_right = false;
            this.chrg_hall = false;
            this.v_bat = 0.0f;
        }

        public ControlDataMsg(double linear_distance, double angular_distance, double dt, double inductive_prox_left_filtered, double inductive_prox_right_filtered, bool ir_aluminum_lf, bool ir_aluminum_rf, bool ir_aluminum_lr, bool ir_aluminum_rr, bool ir_retro_left, bool ir_retro_right, bool chrg_hall, float v_bat)
        {
            this.linear_distance = linear_distance;
            this.angular_distance = angular_distance;
            this.dt = dt;
            this.inductive_prox_left_filtered = inductive_prox_left_filtered;
            this.inductive_prox_right_filtered = inductive_prox_right_filtered;
            this.ir_aluminum_lf = ir_aluminum_lf;
            this.ir_aluminum_rf = ir_aluminum_rf;
            this.ir_aluminum_lr = ir_aluminum_lr;
            this.ir_aluminum_rr = ir_aluminum_rr;
            this.ir_retro_left = ir_retro_left;
            this.ir_retro_right = ir_retro_right;
            this.chrg_hall = chrg_hall;
            this.v_bat = v_bat;
        }

        public static ControlDataMsg Deserialize(MessageDeserializer deserializer) => new ControlDataMsg(deserializer);

        private ControlDataMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.linear_distance);
            deserializer.Read(out this.angular_distance);
            deserializer.Read(out this.dt);
            deserializer.Read(out this.inductive_prox_left_filtered);
            deserializer.Read(out this.inductive_prox_right_filtered);
            deserializer.Read(out this.ir_aluminum_lf);
            deserializer.Read(out this.ir_aluminum_rf);
            deserializer.Read(out this.ir_aluminum_lr);
            deserializer.Read(out this.ir_aluminum_rr);
            deserializer.Read(out this.ir_retro_left);
            deserializer.Read(out this.ir_retro_right);
            deserializer.Read(out this.chrg_hall);
            deserializer.Read(out this.v_bat);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.linear_distance);
            serializer.Write(this.angular_distance);
            serializer.Write(this.dt);
            serializer.Write(this.inductive_prox_left_filtered);
            serializer.Write(this.inductive_prox_right_filtered);
            serializer.Write(this.ir_aluminum_lf);
            serializer.Write(this.ir_aluminum_rf);
            serializer.Write(this.ir_aluminum_lr);
            serializer.Write(this.ir_aluminum_rr);
            serializer.Write(this.ir_retro_left);
            serializer.Write(this.ir_retro_right);
            serializer.Write(this.chrg_hall);
            serializer.Write(this.v_bat);
        }

        public override string ToString()
        {
            return "ControlDataMsg: " +
            "\nlinear_distance: " + linear_distance.ToString() +
            "\nangular_distance: " + angular_distance.ToString() +
            "\ndt: " + dt.ToString() +
            "\ninductive_prox_left_filtered: " + inductive_prox_left_filtered.ToString() +
            "\ninductive_prox_right_filtered: " + inductive_prox_right_filtered.ToString() +
            "\nir_aluminum_lf: " + ir_aluminum_lf.ToString() +
            "\nir_aluminum_rf: " + ir_aluminum_rf.ToString() +
            "\nir_aluminum_lr: " + ir_aluminum_lr.ToString() +
            "\nir_aluminum_rr: " + ir_aluminum_rr.ToString() +
            "\nir_retro_left: " + ir_retro_left.ToString() +
            "\nir_retro_right: " + ir_retro_right.ToString() +
            "\nchrg_hall: " + chrg_hall.ToString() +
            "\nv_bat: " + v_bat.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
