//Do not edit! This file was generated by Unity-ROS MessageGeneration.

using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RoboteqDiff
{
    [Serializable]
    public class ErrorDataMsg : Message
    {
        public const string k_RosMessageName = "roboteq_diff_msgs/ErrorData";
        public override string RosMessageName => k_RosMessageName;

        public bool error_status;
        public uint error_code;

        public ErrorDataMsg()
        {
            error_status = false;
            error_code = 0;
        }

        public ErrorDataMsg(bool error_status, uint error_code)
        {
            this.error_status = error_status;
            this.error_code = error_code;
        }

        public static ErrorDataMsg Deserialize(MessageDeserializer deserializer)
        {
            return new ErrorDataMsg(deserializer);
        }

        private ErrorDataMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out error_status);
            deserializer.Read(out error_code);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(error_status);
            serializer.Write(error_code);
        }

        public override string ToString()
        {
            return "ErrorDataMsg: " +
                   "\nerror_status: " + error_status.ToString() +
                   "\nerror_code: " + error_code.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}