//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RoboteqDiff
{
    [Serializable]
    public class TuningDataMsg : Message
    {
        public const string k_RosMessageName = "roboteq_diff_msgs/TuningData";
        public override string RosMessageName => k_RosMessageName;

        public int measured_speed_lf;
        public int measured_speed_rf;
        public int measured_speed_lr;
        public int measured_speed_rr;
        public int measured_speed_bf;
        public int measured_speed_br;
        public int track_error_lf;
        public int track_error_rf;
        public int track_error_lr;
        public int track_error_rr;
        public int track_error_bf;
        public int track_error_br;

        public TuningDataMsg()
        {
            this.measured_speed_lf = 0;
            this.measured_speed_rf = 0;
            this.measured_speed_lr = 0;
            this.measured_speed_rr = 0;
            this.measured_speed_bf = 0;
            this.measured_speed_br = 0;
            this.track_error_lf = 0;
            this.track_error_rf = 0;
            this.track_error_lr = 0;
            this.track_error_rr = 0;
            this.track_error_bf = 0;
            this.track_error_br = 0;
        }

        public TuningDataMsg(int measured_speed_lf, int measured_speed_rf, int measured_speed_lr, int measured_speed_rr, int measured_speed_bf, int measured_speed_br, int track_error_lf, int track_error_rf, int track_error_lr, int track_error_rr, int track_error_bf, int track_error_br)
        {
            this.measured_speed_lf = measured_speed_lf;
            this.measured_speed_rf = measured_speed_rf;
            this.measured_speed_lr = measured_speed_lr;
            this.measured_speed_rr = measured_speed_rr;
            this.measured_speed_bf = measured_speed_bf;
            this.measured_speed_br = measured_speed_br;
            this.track_error_lf = track_error_lf;
            this.track_error_rf = track_error_rf;
            this.track_error_lr = track_error_lr;
            this.track_error_rr = track_error_rr;
            this.track_error_bf = track_error_bf;
            this.track_error_br = track_error_br;
        }

        public static TuningDataMsg Deserialize(MessageDeserializer deserializer) => new TuningDataMsg(deserializer);

        private TuningDataMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.measured_speed_lf);
            deserializer.Read(out this.measured_speed_rf);
            deserializer.Read(out this.measured_speed_lr);
            deserializer.Read(out this.measured_speed_rr);
            deserializer.Read(out this.measured_speed_bf);
            deserializer.Read(out this.measured_speed_br);
            deserializer.Read(out this.track_error_lf);
            deserializer.Read(out this.track_error_rf);
            deserializer.Read(out this.track_error_lr);
            deserializer.Read(out this.track_error_rr);
            deserializer.Read(out this.track_error_bf);
            deserializer.Read(out this.track_error_br);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.measured_speed_lf);
            serializer.Write(this.measured_speed_rf);
            serializer.Write(this.measured_speed_lr);
            serializer.Write(this.measured_speed_rr);
            serializer.Write(this.measured_speed_bf);
            serializer.Write(this.measured_speed_br);
            serializer.Write(this.track_error_lf);
            serializer.Write(this.track_error_rf);
            serializer.Write(this.track_error_lr);
            serializer.Write(this.track_error_rr);
            serializer.Write(this.track_error_bf);
            serializer.Write(this.track_error_br);
        }

        public override string ToString()
        {
            return "TuningDataMsg: " +
            "\nmeasured_speed_lf: " + measured_speed_lf.ToString() +
            "\nmeasured_speed_rf: " + measured_speed_rf.ToString() +
            "\nmeasured_speed_lr: " + measured_speed_lr.ToString() +
            "\nmeasured_speed_rr: " + measured_speed_rr.ToString() +
            "\nmeasured_speed_bf: " + measured_speed_bf.ToString() +
            "\nmeasured_speed_br: " + measured_speed_br.ToString() +
            "\ntrack_error_lf: " + track_error_lf.ToString() +
            "\ntrack_error_rf: " + track_error_rf.ToString() +
            "\ntrack_error_lr: " + track_error_lr.ToString() +
            "\ntrack_error_rr: " + track_error_rr.ToString() +
            "\ntrack_error_bf: " + track_error_bf.ToString() +
            "\ntrack_error_br: " + track_error_br.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
