//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur
{
    [Serializable]
    public class AnalogMsg : Message
    {
        public const string k_RosMessageName = "ur_msgs/Analog";
        public override string RosMessageName => k_RosMessageName;

        public const byte VOLTAGE = 0;
        public const byte CURRENT = 1;
        public byte pin;
        public byte domain;
        //  can be VOLTAGE or CURRENT
        public float state;

        public AnalogMsg()
        {
            this.pin = 0;
            this.domain = 0;
            this.state = 0.0f;
        }

        public AnalogMsg(byte pin, byte domain, float state)
        {
            this.pin = pin;
            this.domain = domain;
            this.state = state;
        }

        public static AnalogMsg Deserialize(MessageDeserializer deserializer) => new AnalogMsg(deserializer);

        private AnalogMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.pin);
            deserializer.Read(out this.domain);
            deserializer.Read(out this.state);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pin);
            serializer.Write(this.domain);
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "AnalogMsg: " +
            "\npin: " + pin.ToString() +
            "\ndomain: " + domain.ToString() +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
