//Do not edit! This file was generated by Unity-ROS MessageGeneration.

using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur
{
    [Serializable]
    public class AnalogMsg : Message
    {
        public const string k_RosMessageName = "ur_msgs/Analog";
        public override string RosMessageName => k_RosMessageName;

        public const byte VOLTAGE = 0;
        public const byte CURRENT = 1;
        public byte pin;

        public byte domain;

        //  can be VOLTAGE or CURRENT
        public float state;

        public AnalogMsg()
        {
            pin = 0;
            domain = 0;
            state = 0.0f;
        }

        public AnalogMsg(byte pin, byte domain, float state)
        {
            this.pin = pin;
            this.domain = domain;
            this.state = state;
        }

        public static AnalogMsg Deserialize(MessageDeserializer deserializer)
        {
            return new AnalogMsg(deserializer);
        }

        private AnalogMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out pin);
            deserializer.Read(out domain);
            deserializer.Read(out state);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(pin);
            serializer.Write(domain);
            serializer.Write(state);
        }

        public override string ToString()
        {
            return "AnalogMsg: " +
                   "\npin: " + pin.ToString() +
                   "\ndomain: " + domain.ToString() +
                   "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}