//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur
{
    [Serializable]
    public class DigitalMsg : Message
    {
        public const string k_RosMessageName = "ur_msgs/Digital";
        public override string RosMessageName => k_RosMessageName;

        public byte pin;
        public bool state;

        public DigitalMsg()
        {
            this.pin = 0;
            this.state = false;
        }

        public DigitalMsg(byte pin, bool state)
        {
            this.pin = pin;
            this.state = state;
        }

        public static DigitalMsg Deserialize(MessageDeserializer deserializer) => new DigitalMsg(deserializer);

        private DigitalMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.pin);
            deserializer.Read(out this.state);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pin);
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "DigitalMsg: " +
            "\npin: " + pin.ToString() +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
