//Do not edit! This file was generated by Unity-ROS MessageGeneration.

using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur
{
    [Serializable]
    public class IOStatesMsg : Message
    {
        public const string k_RosMessageName = "ur_msgs/IOStates";
        public override string RosMessageName => k_RosMessageName;

        public DigitalMsg[] digital_in_states;
        public DigitalMsg[] digital_out_states;
        public DigitalMsg[] flag_states;
        public AnalogMsg[] analog_in_states;
        public AnalogMsg[] analog_out_states;

        public IOStatesMsg()
        {
            digital_in_states = new DigitalMsg[0];
            digital_out_states = new DigitalMsg[0];
            flag_states = new DigitalMsg[0];
            analog_in_states = new AnalogMsg[0];
            analog_out_states = new AnalogMsg[0];
        }

        public IOStatesMsg(DigitalMsg[] digital_in_states, DigitalMsg[] digital_out_states, DigitalMsg[] flag_states,
            AnalogMsg[] analog_in_states, AnalogMsg[] analog_out_states)
        {
            this.digital_in_states = digital_in_states;
            this.digital_out_states = digital_out_states;
            this.flag_states = flag_states;
            this.analog_in_states = analog_in_states;
            this.analog_out_states = analog_out_states;
        }

        public static IOStatesMsg Deserialize(MessageDeserializer deserializer)
        {
            return new IOStatesMsg(deserializer);
        }

        private IOStatesMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out digital_in_states, DigitalMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out digital_out_states, DigitalMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out flag_states, DigitalMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out analog_in_states, AnalogMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out analog_out_states, AnalogMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(digital_in_states);
            serializer.Write(digital_in_states);
            serializer.WriteLength(digital_out_states);
            serializer.Write(digital_out_states);
            serializer.WriteLength(flag_states);
            serializer.Write(flag_states);
            serializer.WriteLength(analog_in_states);
            serializer.Write(analog_in_states);
            serializer.WriteLength(analog_out_states);
            serializer.Write(analog_out_states);
        }

        public override string ToString()
        {
            return "IOStatesMsg: " +
                   "\ndigital_in_states: " + string.Join(", ", digital_in_states.ToList()) +
                   "\ndigital_out_states: " + string.Join(", ", digital_out_states.ToList()) +
                   "\nflag_states: " + string.Join(", ", flag_states.ToList()) +
                   "\nanalog_in_states: " + string.Join(", ", analog_in_states.ToList()) +
                   "\nanalog_out_states: " + string.Join(", ", analog_out_states.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}