//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur
{
    [Serializable]
    public class RobotModeDataMsgMsg : Message
    {
        public const string k_RosMessageName = "ur_msgs/RobotModeDataMsg";
        public override string RosMessageName => k_RosMessageName;

        //  This data structure contains the RobotModeData structure
        //  used by the Universal Robots controller
        // 
        //  This data structure is send at 10 Hz on TCP port 30002
        // 
        //  Note: this message does not carry all fields from the RobotModeData structure as broadcast by the robot controller, but a subset.
        public ulong timestamp;
        public bool is_robot_connected;
        public bool is_real_robot_enabled;
        public bool is_power_on_robot;
        public bool is_emergency_stopped;
        public bool is_protective_stopped;
        public bool is_program_running;
        public bool is_program_paused;

        public RobotModeDataMsgMsg()
        {
            this.timestamp = 0;
            this.is_robot_connected = false;
            this.is_real_robot_enabled = false;
            this.is_power_on_robot = false;
            this.is_emergency_stopped = false;
            this.is_protective_stopped = false;
            this.is_program_running = false;
            this.is_program_paused = false;
        }

        public RobotModeDataMsgMsg(ulong timestamp, bool is_robot_connected, bool is_real_robot_enabled, bool is_power_on_robot, bool is_emergency_stopped, bool is_protective_stopped, bool is_program_running, bool is_program_paused)
        {
            this.timestamp = timestamp;
            this.is_robot_connected = is_robot_connected;
            this.is_real_robot_enabled = is_real_robot_enabled;
            this.is_power_on_robot = is_power_on_robot;
            this.is_emergency_stopped = is_emergency_stopped;
            this.is_protective_stopped = is_protective_stopped;
            this.is_program_running = is_program_running;
            this.is_program_paused = is_program_paused;
        }

        public static RobotModeDataMsgMsg Deserialize(MessageDeserializer deserializer) => new RobotModeDataMsgMsg(deserializer);

        private RobotModeDataMsgMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.timestamp);
            deserializer.Read(out this.is_robot_connected);
            deserializer.Read(out this.is_real_robot_enabled);
            deserializer.Read(out this.is_power_on_robot);
            deserializer.Read(out this.is_emergency_stopped);
            deserializer.Read(out this.is_protective_stopped);
            deserializer.Read(out this.is_program_running);
            deserializer.Read(out this.is_program_paused);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.timestamp);
            serializer.Write(this.is_robot_connected);
            serializer.Write(this.is_real_robot_enabled);
            serializer.Write(this.is_power_on_robot);
            serializer.Write(this.is_emergency_stopped);
            serializer.Write(this.is_protective_stopped);
            serializer.Write(this.is_program_running);
            serializer.Write(this.is_program_paused);
        }

        public override string ToString()
        {
            return "RobotModeDataMsgMsg: " +
            "\ntimestamp: " + timestamp.ToString() +
            "\nis_robot_connected: " + is_robot_connected.ToString() +
            "\nis_real_robot_enabled: " + is_real_robot_enabled.ToString() +
            "\nis_power_on_robot: " + is_power_on_robot.ToString() +
            "\nis_emergency_stopped: " + is_emergency_stopped.ToString() +
            "\nis_protective_stopped: " + is_protective_stopped.ToString() +
            "\nis_program_running: " + is_program_running.ToString() +
            "\nis_program_paused: " + is_program_paused.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
