//Do not edit! This file was generated by Unity-ROS MessageGeneration.

using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur
{
    [Serializable]
    public class ToolDataMsgMsg : Message
    {
        public const string k_RosMessageName = "ur_msgs/ToolDataMsg";
        public override string RosMessageName => k_RosMessageName;

        //  This data structure contains the ToolData structure
        //  used by the Universal Robots controller
        public const sbyte ANALOG_INPUT_RANGE_CURRENT = 0;
        public const sbyte ANALOG_INPUT_RANGE_VOLTAGE = 1;

        public sbyte analog_input_range2;

        //  one of ANALOG_INPUT_RANGE_*
        public sbyte analog_input_range3;

        //  one of ANALOG_INPUT_RANGE_*
        public double analog_input2;
        public double analog_input3;
        public float tool_voltage_48v;
        public byte tool_output_voltage;
        public float tool_current;
        public float tool_temperature;
        public const byte TOOL_BOOTLOADER_MODE = 249;
        public const byte TOOL_RUNNING_MODE = 253;
        public const byte TOOL_IDLE_MODE = 255;

        public byte tool_mode;
        //  one of TOOL_*

        public ToolDataMsgMsg()
        {
            analog_input_range2 = 0;
            analog_input_range3 = 0;
            analog_input2 = 0.0;
            analog_input3 = 0.0;
            tool_voltage_48v = 0.0f;
            tool_output_voltage = 0;
            tool_current = 0.0f;
            tool_temperature = 0.0f;
            tool_mode = 0;
        }

        public ToolDataMsgMsg(sbyte analog_input_range2, sbyte analog_input_range3, double analog_input2,
            double analog_input3, float tool_voltage_48v, byte tool_output_voltage, float tool_current,
            float tool_temperature, byte tool_mode)
        {
            this.analog_input_range2 = analog_input_range2;
            this.analog_input_range3 = analog_input_range3;
            this.analog_input2 = analog_input2;
            this.analog_input3 = analog_input3;
            this.tool_voltage_48v = tool_voltage_48v;
            this.tool_output_voltage = tool_output_voltage;
            this.tool_current = tool_current;
            this.tool_temperature = tool_temperature;
            this.tool_mode = tool_mode;
        }

        public static ToolDataMsgMsg Deserialize(MessageDeserializer deserializer)
        {
            return new ToolDataMsgMsg(deserializer);
        }

        private ToolDataMsgMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out analog_input_range2);
            deserializer.Read(out analog_input_range3);
            deserializer.Read(out analog_input2);
            deserializer.Read(out analog_input3);
            deserializer.Read(out tool_voltage_48v);
            deserializer.Read(out tool_output_voltage);
            deserializer.Read(out tool_current);
            deserializer.Read(out tool_temperature);
            deserializer.Read(out tool_mode);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(analog_input_range2);
            serializer.Write(analog_input_range3);
            serializer.Write(analog_input2);
            serializer.Write(analog_input3);
            serializer.Write(tool_voltage_48v);
            serializer.Write(tool_output_voltage);
            serializer.Write(tool_current);
            serializer.Write(tool_temperature);
            serializer.Write(tool_mode);
        }

        public override string ToString()
        {
            return "ToolDataMsgMsg: " +
                   "\nanalog_input_range2: " + analog_input_range2.ToString() +
                   "\nanalog_input_range3: " + analog_input_range3.ToString() +
                   "\nanalog_input2: " + analog_input2.ToString() +
                   "\nanalog_input3: " + analog_input3.ToString() +
                   "\ntool_voltage_48v: " + tool_voltage_48v.ToString() +
                   "\ntool_output_voltage: " + tool_output_voltage.ToString() +
                   "\ntool_current: " + tool_current.ToString() +
                   "\ntool_temperature: " + tool_temperature.ToString() +
                   "\ntool_mode: " + tool_mode.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}