//Do not edit! This file was generated by Unity-ROS MessageGeneration.

using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur
{
    [Serializable]
    public class SetSpeedSliderFractionRequest : Message
    {
        public const string k_RosMessageName = "ur_msgs/SetSpeedSliderFraction";
        public override string RosMessageName => k_RosMessageName;

        //  Set the speed slider on the teach pendant to the specified value.
        // 
        //  Values for 'speed_slider_fraction' must be from [0; 1.0]; values outside this
        //  valid range will result in an error being returned to the caller.
        public double speed_slider_fraction;

        public SetSpeedSliderFractionRequest()
        {
            speed_slider_fraction = 0.0;
        }

        public SetSpeedSliderFractionRequest(double speed_slider_fraction)
        {
            this.speed_slider_fraction = speed_slider_fraction;
        }

        public static SetSpeedSliderFractionRequest Deserialize(MessageDeserializer deserializer)
        {
            return new SetSpeedSliderFractionRequest(deserializer);
        }

        private SetSpeedSliderFractionRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out speed_slider_fraction);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(speed_slider_fraction);
        }

        public override string ToString()
        {
            return "SetSpeedSliderFractionRequest: " +
                   "\nspeed_slider_fraction: " + speed_slider_fraction.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}