//Do not edit! This file was generated by Unity-ROS MessageGeneration.

using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur5Intpro
{
    [Serializable]
    public class CamPoseMsg : Message
    {
        public const string k_RosMessageName = "ur5_intpro/CamPose";
        public override string RosMessageName => k_RosMessageName;

        public double x;
        public double y;
        public double z;
        public double x_;
        public double y_;
        public double z_;
        public double w_;

        public CamPoseMsg()
        {
            x = 0.0;
            y = 0.0;
            z = 0.0;
            x_ = 0.0;
            y_ = 0.0;
            z_ = 0.0;
            w_ = 0.0;
        }

        public CamPoseMsg(double x, double y, double z, double x_, double y_, double z_, double w_)
        {
            this.x = x;
            this.y = y;
            this.z = z;
            this.x_ = x_;
            this.y_ = y_;
            this.z_ = z_;
            this.w_ = w_;
        }

        public static CamPoseMsg Deserialize(MessageDeserializer deserializer)
        {
            return new CamPoseMsg(deserializer);
        }

        private CamPoseMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out x);
            deserializer.Read(out y);
            deserializer.Read(out z);
            deserializer.Read(out x_);
            deserializer.Read(out y_);
            deserializer.Read(out z_);
            deserializer.Read(out w_);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(x);
            serializer.Write(y);
            serializer.Write(z);
            serializer.Write(x_);
            serializer.Write(y_);
            serializer.Write(z_);
            serializer.Write(w_);
        }

        public override string ToString()
        {
            return "CamPoseMsg: " +
                   "\nx: " + x.ToString() +
                   "\ny: " + y.ToString() +
                   "\nz: " + z.ToString() +
                   "\nx_: " + x_.ToString() +
                   "\ny_: " + y_.ToString() +
                   "\nz_: " + z_.ToString() +
                   "\nw_: " + w_.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}