//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur5Intpro
{
    [Serializable]
    public class ImageSrcMatMsg : Message
    {
        public const string k_RosMessageName = "ur5_intpro/ImageSrcMat";
        public override string RosMessageName => k_RosMessageName;

        public Sensor.ImageMsg Image;
        public double[] x;
        public double[] y;

        public ImageSrcMatMsg()
        {
            this.Image = new Sensor.ImageMsg();
            this.x = new double[4];
            this.y = new double[4];
        }

        public ImageSrcMatMsg(Sensor.ImageMsg Image, double[] x, double[] y)
        {
            this.Image = Image;
            this.x = x;
            this.y = y;
        }

        public static ImageSrcMatMsg Deserialize(MessageDeserializer deserializer) => new ImageSrcMatMsg(deserializer);

        private ImageSrcMatMsg(MessageDeserializer deserializer)
        {
            this.Image = Sensor.ImageMsg.Deserialize(deserializer);
            deserializer.Read(out this.x, sizeof(double), 4);
            deserializer.Read(out this.y, sizeof(double), 4);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.Image);
            serializer.Write(this.x);
            serializer.Write(this.y);
        }

        public override string ToString()
        {
            return "ImageSrcMatMsg: " +
            "\nImage: " + Image.ToString() +
            "\nx: " + System.String.Join(", ", x.ToList()) +
            "\ny: " + System.String.Join(", ", y.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
