//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur5Intpro
{
    [Serializable]
    public class PrimitiveMsg : Message
    {
        public const string k_RosMessageName = "ur5_intpro/Primitive";
        public override string RosMessageName => k_RosMessageName;

        public byte id;

        public PrimitiveMsg()
        {
            this.id = 0;
        }

        public PrimitiveMsg(byte id)
        {
            this.id = id;
        }

        public static PrimitiveMsg Deserialize(MessageDeserializer deserializer) => new PrimitiveMsg(deserializer);

        private PrimitiveMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
        }

        public override string ToString()
        {
            return "PrimitiveMsg: " +
            "\nid: " + id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
