//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur5Intpro
{
    [Serializable]
    public class RGBXYImageSrcMatMsg : Message
    {
        public const string k_RosMessageName = "ur5_intpro/RGBXYImageSrcMat";
        public override string RosMessageName => k_RosMessageName;

        public RGBXYSEGMsg rgbxyseg;
        public ImageSrcMatMsg imagsrcmat;

        public RGBXYImageSrcMatMsg()
        {
            this.rgbxyseg = new RGBXYSEGMsg();
            this.imagsrcmat = new ImageSrcMatMsg();
        }

        public RGBXYImageSrcMatMsg(RGBXYSEGMsg rgbxyseg, ImageSrcMatMsg imagsrcmat)
        {
            this.rgbxyseg = rgbxyseg;
            this.imagsrcmat = imagsrcmat;
        }

        public static RGBXYImageSrcMatMsg Deserialize(MessageDeserializer deserializer) => new RGBXYImageSrcMatMsg(deserializer);

        private RGBXYImageSrcMatMsg(MessageDeserializer deserializer)
        {
            this.rgbxyseg = RGBXYSEGMsg.Deserialize(deserializer);
            this.imagsrcmat = ImageSrcMatMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.rgbxyseg);
            serializer.Write(this.imagsrcmat);
        }

        public override string ToString()
        {
            return "RGBXYImageSrcMatMsg: " +
            "\nrgbxyseg: " + rgbxyseg.ToString() +
            "\nimagsrcmat: " + imagsrcmat.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
