//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur5Intpro
{
    [Serializable]
    public class RGBXYSEGMsg : Message
    {
        public const string k_RosMessageName = "ur5_intpro/RGBXYSEG";
        public override string RosMessageName => k_RosMessageName;

        public Sensor.ImageMsg Image;
        public float[] xy;
        public float[] xyz;
        public string[] obj_names;

        public RGBXYSEGMsg()
        {
            this.Image = new Sensor.ImageMsg();
            this.xy = new float[0];
            this.xyz = new float[0];
            this.obj_names = new string[0];
        }

        public RGBXYSEGMsg(Sensor.ImageMsg Image, float[] xy, float[] xyz, string[] obj_names)
        {
            this.Image = Image;
            this.xy = xy;
            this.xyz = xyz;
            this.obj_names = obj_names;
        }

        public static RGBXYSEGMsg Deserialize(MessageDeserializer deserializer) => new RGBXYSEGMsg(deserializer);

        private RGBXYSEGMsg(MessageDeserializer deserializer)
        {
            this.Image = Sensor.ImageMsg.Deserialize(deserializer);
            deserializer.Read(out this.xy, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.xyz, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.obj_names, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.Image);
            serializer.WriteLength(this.xy);
            serializer.Write(this.xy);
            serializer.WriteLength(this.xyz);
            serializer.Write(this.xyz);
            serializer.WriteLength(this.obj_names);
            serializer.Write(this.obj_names);
        }

        public override string ToString()
        {
            return "RGBXYSEGMsg: " +
            "\nImage: " + Image.ToString() +
            "\nxy: " + System.String.Join(", ", xy.ToList()) +
            "\nxyz: " + System.String.Join(", ", xyz.ToList()) +
            "\nobj_names: " + System.String.Join(", ", obj_names.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
