//Do not edit! This file was generated by Unity-ROS MessageGeneration.

using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur5Intpro
{
    [Serializable]
    public class RobotiqMsg : Message
    {
        public const string k_RosMessageName = "ur5_intpro/Robotiq";
        public override string RosMessageName => k_RosMessageName;

        public double data;

        public RobotiqMsg()
        {
            data = 0.0;
        }

        public RobotiqMsg(double data)
        {
            this.data = data;
        }

        public static RobotiqMsg Deserialize(MessageDeserializer deserializer)
        {
            return new RobotiqMsg(deserializer);
        }

        private RobotiqMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out data);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(data);
        }

        public override string ToString()
        {
            return "RobotiqMsg: " +
                   "\ndata: " + data.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}