//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur5Intpro
{
    [Serializable]
    public class SmartwatchMsg : Message
    {
        public const string k_RosMessageName = "ur5_intpro/Smartwatch";
        public override string RosMessageName => k_RosMessageName;

        public float[] data;

        public SmartwatchMsg()
        {
            this.data = new float[0];
        }

        public SmartwatchMsg(float[] data)
        {
            this.data = data;
        }

        public static SmartwatchMsg Deserialize(MessageDeserializer deserializer) => new SmartwatchMsg(deserializer);

        private SmartwatchMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.data, sizeof(float), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.data);
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "SmartwatchMsg: " +
            "\ndata: " + System.String.Join(", ", data.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
