//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur5Intpro
{
    [Serializable]
    public class SpacemouseMsg : Message
    {
        public const string k_RosMessageName = "ur5_intpro/Spacemouse";
        public override string RosMessageName => k_RosMessageName;

        public double[] xyz;
        public double[] rpy;
        public bool lbutton;
        public bool rbutton;

        public SpacemouseMsg()
        {
            this.xyz = new double[3];
            this.rpy = new double[3];
            this.lbutton = false;
            this.rbutton = false;
        }

        public SpacemouseMsg(double[] xyz, double[] rpy, bool lbutton, bool rbutton)
        {
            this.xyz = xyz;
            this.rpy = rpy;
            this.lbutton = lbutton;
            this.rbutton = rbutton;
        }

        public static SpacemouseMsg Deserialize(MessageDeserializer deserializer) => new SpacemouseMsg(deserializer);

        private SpacemouseMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.xyz, sizeof(double), 3);
            deserializer.Read(out this.rpy, sizeof(double), 3);
            deserializer.Read(out this.lbutton);
            deserializer.Read(out this.rbutton);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.xyz);
            serializer.Write(this.rpy);
            serializer.Write(this.lbutton);
            serializer.Write(this.rbutton);
        }

        public override string ToString()
        {
            return "SpacemouseMsg: " +
            "\nxyz: " + System.String.Join(", ", xyz.ToList()) +
            "\nrpy: " + System.String.Join(", ", rpy.ToList()) +
            "\nlbutton: " + lbutton.ToString() +
            "\nrbutton: " + rbutton.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
