//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur5Intpro
{
    [Serializable]
    public class TeleopDeltaPoseMsg : Message
    {
        public const string k_RosMessageName = "ur5_intpro/TeleopDeltaPose";
        public override string RosMessageName => k_RosMessageName;

        public double dx;
        public double dy;
        public double dz;
        public double dx_;
        public double dy_;
        public double dz_;
        public double dw_;

        public TeleopDeltaPoseMsg()
        {
            this.dx = 0.0;
            this.dy = 0.0;
            this.dz = 0.0;
            this.dx_ = 0.0;
            this.dy_ = 0.0;
            this.dz_ = 0.0;
            this.dw_ = 0.0;
        }

        public TeleopDeltaPoseMsg(double dx, double dy, double dz, double dx_, double dy_, double dz_, double dw_)
        {
            this.dx = dx;
            this.dy = dy;
            this.dz = dz;
            this.dx_ = dx_;
            this.dy_ = dy_;
            this.dz_ = dz_;
            this.dw_ = dw_;
        }

        public static TeleopDeltaPoseMsg Deserialize(MessageDeserializer deserializer) => new TeleopDeltaPoseMsg(deserializer);

        private TeleopDeltaPoseMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.dx);
            deserializer.Read(out this.dy);
            deserializer.Read(out this.dz);
            deserializer.Read(out this.dx_);
            deserializer.Read(out this.dy_);
            deserializer.Read(out this.dz_);
            deserializer.Read(out this.dw_);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.dx);
            serializer.Write(this.dy);
            serializer.Write(this.dz);
            serializer.Write(this.dx_);
            serializer.Write(this.dy_);
            serializer.Write(this.dz_);
            serializer.Write(this.dw_);
        }

        public override string ToString()
        {
            return "TeleopDeltaPoseMsg: " +
            "\ndx: " + dx.ToString() +
            "\ndy: " + dy.ToString() +
            "\ndz: " + dz.ToString() +
            "\ndx_: " + dx_.ToString() +
            "\ndy_: " + dy_.ToString() +
            "\ndz_: " + dz_.ToString() +
            "\ndw_: " + dw_.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
