//Do not edit! This file was generated by Unity-ROS MessageGeneration.

using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur5Intpro
{
    [Serializable]
    public class Ur5JointsMsg : Message
    {
        public const string k_RosMessageName = "ur5_intpro/Ur5Joints";
        public override string RosMessageName => k_RosMessageName;

        public double[] joints;

        public Ur5JointsMsg()
        {
            joints = new double[6];
        }

        public Ur5JointsMsg(double[] joints)
        {
            this.joints = joints;
        }

        public static Ur5JointsMsg Deserialize(MessageDeserializer deserializer)
        {
            return new Ur5JointsMsg(deserializer);
        }

        private Ur5JointsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out joints, sizeof(double), 6);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(joints);
        }

        public override string ToString()
        {
            return "Ur5JointsMsg: " +
                   "\njoints: " + string.Join(", ", joints.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}