//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur5Intpro
{
    [Serializable]
    public class V2DataMsg : Message
    {
        public const string k_RosMessageName = "ur5_intpro/v2Data";
        public override string RosMessageName => k_RosMessageName;

        public float[] x_image;
        public float[] y_image;
        public float[] x_world;
        public float[] y_world;
        public float[] z_world;
        public float[] joint_angles;

        public V2DataMsg()
        {
            this.x_image = new float[4];
            this.y_image = new float[4];
            this.x_world = new float[4];
            this.y_world = new float[4];
            this.z_world = new float[4];
            this.joint_angles = new float[7];
        }

        public V2DataMsg(float[] x_image, float[] y_image, float[] x_world, float[] y_world, float[] z_world, float[] joint_angles)
        {
            this.x_image = x_image;
            this.y_image = y_image;
            this.x_world = x_world;
            this.y_world = y_world;
            this.z_world = z_world;
            this.joint_angles = joint_angles;
        }

        public static V2DataMsg Deserialize(MessageDeserializer deserializer) => new V2DataMsg(deserializer);

        private V2DataMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.x_image, sizeof(float), 4);
            deserializer.Read(out this.y_image, sizeof(float), 4);
            deserializer.Read(out this.x_world, sizeof(float), 4);
            deserializer.Read(out this.y_world, sizeof(float), 4);
            deserializer.Read(out this.z_world, sizeof(float), 4);
            deserializer.Read(out this.joint_angles, sizeof(float), 7);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.x_image);
            serializer.Write(this.y_image);
            serializer.Write(this.x_world);
            serializer.Write(this.y_world);
            serializer.Write(this.z_world);
            serializer.Write(this.joint_angles);
        }

        public override string ToString()
        {
            return "V2DataMsg: " +
            "\nx_image: " + System.String.Join(", ", x_image.ToList()) +
            "\ny_image: " + System.String.Join(", ", y_image.ToList()) +
            "\nx_world: " + System.String.Join(", ", x_world.ToList()) +
            "\ny_world: " + System.String.Join(", ", y_world.ToList()) +
            "\nz_world: " + System.String.Join(", ", z_world.ToList()) +
            "\njoint_angles: " + System.String.Join(", ", joint_angles.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
