//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur5Intpro
{
    [Serializable]
    public class V3DataMsg : Message
    {
        public const string k_RosMessageName = "ur5_intpro/v3Data";
        public override string RosMessageName => k_RosMessageName;

        public float[] x_world;
        public float[] y_world;
        public float[] z_world;
        public string[] object_names;
        public float[] joint_angles;

        public V3DataMsg()
        {
            this.x_world = new float[0];
            this.y_world = new float[0];
            this.z_world = new float[0];
            this.object_names = new string[0];
            this.joint_angles = new float[7];
        }

        public V3DataMsg(float[] x_world, float[] y_world, float[] z_world, string[] object_names, float[] joint_angles)
        {
            this.x_world = x_world;
            this.y_world = y_world;
            this.z_world = z_world;
            this.object_names = object_names;
            this.joint_angles = joint_angles;
        }

        public static V3DataMsg Deserialize(MessageDeserializer deserializer) => new V3DataMsg(deserializer);

        private V3DataMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.x_world, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.y_world, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.z_world, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.object_names, deserializer.ReadLength());
            deserializer.Read(out this.joint_angles, sizeof(float), 7);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.x_world);
            serializer.Write(this.x_world);
            serializer.WriteLength(this.y_world);
            serializer.Write(this.y_world);
            serializer.WriteLength(this.z_world);
            serializer.Write(this.z_world);
            serializer.WriteLength(this.object_names);
            serializer.Write(this.object_names);
            serializer.Write(this.joint_angles);
        }

        public override string ToString()
        {
            return "V3DataMsg: " +
            "\nx_world: " + System.String.Join(", ", x_world.ToList()) +
            "\ny_world: " + System.String.Join(", ", y_world.ToList()) +
            "\nz_world: " + System.String.Join(", ", z_world.ToList()) +
            "\nobject_names: " + System.String.Join(", ", object_names.ToList()) +
            "\njoint_angles: " + System.String.Join(", ", joint_angles.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
