//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.IrlRobots
{
    [Serializable]
    public class GSimpleControlMsg : Message
    {
        public const string k_RosMessageName = "irl_robots/gSimpleControl";
        public override string RosMessageName => k_RosMessageName;

        public byte position;
        public byte force;
        public byte speed;

        public GSimpleControlMsg()
        {
            this.position = 0;
            this.force = 0;
            this.speed = 0;
        }

        public GSimpleControlMsg(byte position, byte force, byte speed)
        {
            this.position = position;
            this.force = force;
            this.speed = speed;
        }

        public static GSimpleControlMsg Deserialize(MessageDeserializer deserializer) => new GSimpleControlMsg(deserializer);

        private GSimpleControlMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.position);
            deserializer.Read(out this.force);
            deserializer.Read(out this.speed);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.position);
            serializer.Write(this.force);
            serializer.Write(this.speed);
        }

        public override string ToString()
        {
            return "GSimpleControlMsg: " +
            "\nposition: " + position.ToString() +
            "\nforce: " + force.ToString() +
            "\nspeed: " + speed.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
