//Do not edit! This file was generated by Unity-ROS MessageGeneration.

using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.IrlRobots
{
    [Serializable]
    public class R2fgControlMsg : Message
    {
        public const string k_RosMessageName = "irl_robots/r2fgControl";
        public override string RosMessageName => k_RosMessageName;

        public bool activate;
        public bool go;
        public bool autorelease_open;
        public bool autorelease;
        public byte position;
        public byte speed;
        public byte force;

        public R2fgControlMsg()
        {
            activate = false;
            go = false;
            autorelease_open = false;
            autorelease = false;
            position = 0;
            speed = 0;
            force = 0;
        }

        public R2fgControlMsg(bool activate, bool go, bool autorelease_open, bool autorelease, byte position,
            byte speed, byte force)
        {
            this.activate = activate;
            this.go = go;
            this.autorelease_open = autorelease_open;
            this.autorelease = autorelease;
            this.position = position;
            this.speed = speed;
            this.force = force;
        }

        public static R2fgControlMsg Deserialize(MessageDeserializer deserializer)
        {
            return new R2fgControlMsg(deserializer);
        }

        private R2fgControlMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out activate);
            deserializer.Read(out go);
            deserializer.Read(out autorelease_open);
            deserializer.Read(out autorelease);
            deserializer.Read(out position);
            deserializer.Read(out speed);
            deserializer.Read(out force);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(activate);
            serializer.Write(go);
            serializer.Write(autorelease_open);
            serializer.Write(autorelease);
            serializer.Write(position);
            serializer.Write(speed);
            serializer.Write(force);
        }

        public override string ToString()
        {
            return "R2fgControlMsg: " +
                   "\nactivate: " + activate.ToString() +
                   "\ngo: " + go.ToString() +
                   "\nautorelease_open: " + autorelease_open.ToString() +
                   "\nautorelease: " + autorelease.ToString() +
                   "\nposition: " + position.ToString() +
                   "\nspeed: " + speed.ToString() +
                   "\nforce: " + force.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}