//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.IrlRobots
{
    [Serializable]
    public class RowsMsg : Message
    {
        public const string k_RosMessageName = "irl_robots/rows";
        public override string RosMessageName => k_RosMessageName;

        public double[] values;

        public RowsMsg()
        {
            this.values = new double[0];
        }

        public RowsMsg(double[] values)
        {
            this.values = values;
        }

        public static RowsMsg Deserialize(MessageDeserializer deserializer) => new RowsMsg(deserializer);

        private RowsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.values, sizeof(double), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.values);
            serializer.Write(this.values);
        }

        public override string ToString()
        {
            return "RowsMsg: " +
            "\nvalues: " + System.String.Join(", ", values.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
