//Do not edit! This file was generated by Unity-ROS MessageGeneration.

using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.IrlRobots
{
    [Serializable]
    public class Ur5ControlMsg : Message
    {
        public const string k_RosMessageName = "irl_robots/ur5Control";
        public override string RosMessageName => k_RosMessageName;

        public string command;
        public float[] values;
        public float acceleration;
        public float velocity;
        public float time;
        public float blend;
        public float gain;
        public float lookahead;
        public bool jointcontrol;

        public Ur5ControlMsg()
        {
            command = "";
            values = new float[6];
            acceleration = 0.0f;
            velocity = 0.0f;
            time = 0.0f;
            blend = 0.0f;
            gain = 0.0f;
            lookahead = 0.0f;
            jointcontrol = false;
        }

        public Ur5ControlMsg(string command, float[] values, float acceleration, float velocity, float time,
            float blend, float gain, float lookahead, bool jointcontrol)
        {
            this.command = command;
            this.values = values;
            this.acceleration = acceleration;
            this.velocity = velocity;
            this.time = time;
            this.blend = blend;
            this.gain = gain;
            this.lookahead = lookahead;
            this.jointcontrol = jointcontrol;
        }

        public static Ur5ControlMsg Deserialize(MessageDeserializer deserializer)
        {
            return new Ur5ControlMsg(deserializer);
        }

        private Ur5ControlMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out command);
            deserializer.Read(out values, sizeof(float), 6);
            deserializer.Read(out acceleration);
            deserializer.Read(out velocity);
            deserializer.Read(out time);
            deserializer.Read(out blend);
            deserializer.Read(out gain);
            deserializer.Read(out lookahead);
            deserializer.Read(out jointcontrol);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(command);
            serializer.Write(values);
            serializer.Write(acceleration);
            serializer.Write(velocity);
            serializer.Write(time);
            serializer.Write(blend);
            serializer.Write(gain);
            serializer.Write(lookahead);
            serializer.Write(jointcontrol);
        }

        public override string ToString()
        {
            return "Ur5ControlMsg: " +
                   "\ncommand: " + command.ToString() +
                   "\nvalues: " + string.Join(", ", values.ToList()) +
                   "\nacceleration: " + acceleration.ToString() +
                   "\nvelocity: " + velocity.ToString() +
                   "\ntime: " + time.ToString() +
                   "\nblend: " + blend.ToString() +
                   "\ngain: " + gain.ToString() +
                   "\nlookahead: " + lookahead.ToString() +
                   "\njointcontrol: " + jointcontrol.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}