//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.IrlRobots
{
    [Serializable]
    public class Ur5ControlMsg : Message
    {
        public const string k_RosMessageName = "irl_robots/ur5Control";
        public override string RosMessageName => k_RosMessageName;

        public string command;
        public float[] values;
        public float acceleration;
        public float velocity;
        public float time;
        public float blend;
        public float gain;
        public float lookahead;
        public bool jointcontrol;

        public Ur5ControlMsg()
        {
            this.command = "";
            this.values = new float[6];
            this.acceleration = 0.0f;
            this.velocity = 0.0f;
            this.time = 0.0f;
            this.blend = 0.0f;
            this.gain = 0.0f;
            this.lookahead = 0.0f;
            this.jointcontrol = false;
        }

        public Ur5ControlMsg(string command, float[] values, float acceleration, float velocity, float time, float blend, float gain, float lookahead, bool jointcontrol)
        {
            this.command = command;
            this.values = values;
            this.acceleration = acceleration;
            this.velocity = velocity;
            this.time = time;
            this.blend = blend;
            this.gain = gain;
            this.lookahead = lookahead;
            this.jointcontrol = jointcontrol;
        }

        public static Ur5ControlMsg Deserialize(MessageDeserializer deserializer) => new Ur5ControlMsg(deserializer);

        private Ur5ControlMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.command);
            deserializer.Read(out this.values, sizeof(float), 6);
            deserializer.Read(out this.acceleration);
            deserializer.Read(out this.velocity);
            deserializer.Read(out this.time);
            deserializer.Read(out this.blend);
            deserializer.Read(out this.gain);
            deserializer.Read(out this.lookahead);
            deserializer.Read(out this.jointcontrol);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.command);
            serializer.Write(this.values);
            serializer.Write(this.acceleration);
            serializer.Write(this.velocity);
            serializer.Write(this.time);
            serializer.Write(this.blend);
            serializer.Write(this.gain);
            serializer.Write(this.lookahead);
            serializer.Write(this.jointcontrol);
        }

        public override string ToString()
        {
            return "Ur5ControlMsg: " +
            "\ncommand: " + command.ToString() +
            "\nvalues: " + System.String.Join(", ", values.ToList()) +
            "\nacceleration: " + acceleration.ToString() +
            "\nvelocity: " + velocity.ToString() +
            "\ntime: " + time.ToString() +
            "\nblend: " + blend.ToString() +
            "\ngain: " + gain.ToString() +
            "\nlookahead: " + lookahead.ToString() +
            "\njointcontrol: " + jointcontrol.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
