//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.IrlRobots
{
    [Serializable]
    public class Ur5JointsMsg : Message
    {
        public const string k_RosMessageName = "irl_robots/ur5Joints";
        public override string RosMessageName => k_RosMessageName;

        public double[] positions;
        public double[] velocities;

        public Ur5JointsMsg()
        {
            this.positions = new double[6];
            this.velocities = new double[6];
        }

        public Ur5JointsMsg(double[] positions, double[] velocities)
        {
            this.positions = positions;
            this.velocities = velocities;
        }

        public static Ur5JointsMsg Deserialize(MessageDeserializer deserializer) => new Ur5JointsMsg(deserializer);

        private Ur5JointsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.positions, sizeof(double), 6);
            deserializer.Read(out this.velocities, sizeof(double), 6);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.positions);
            serializer.Write(this.velocities);
        }

        public override string ToString()
        {
            return "Ur5JointsMsg: " +
            "\npositions: " + System.String.Join(", ", positions.ToList()) +
            "\nvelocities: " + System.String.Join(", ", velocities.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
