//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.IrlRobots
{
    [Serializable]
    public class Ur5StatusMsg : Message
    {
        public const string k_RosMessageName = "irl_robots/ur5Status";
        public override string RosMessageName => k_RosMessageName;

        public double mode;
        public double safety_mode;

        public Ur5StatusMsg()
        {
            this.mode = 0.0;
            this.safety_mode = 0.0;
        }

        public Ur5StatusMsg(double mode, double safety_mode)
        {
            this.mode = mode;
            this.safety_mode = safety_mode;
        }

        public static Ur5StatusMsg Deserialize(MessageDeserializer deserializer) => new Ur5StatusMsg(deserializer);

        private Ur5StatusMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.mode);
            deserializer.Read(out this.safety_mode);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.mode);
            serializer.Write(this.safety_mode);
        }

        public override string ToString()
        {
            return "Ur5StatusMsg: " +
            "\nmode: " + mode.ToString() +
            "\nsafety_mode: " + safety_mode.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
