//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.IrlRobots
{
    [Serializable]
    public class Ur5ToolMsg : Message
    {
        public const string k_RosMessageName = "irl_robots/ur5Tool";
        public override string RosMessageName => k_RosMessageName;

        public double[] position;
        public double[] rotation;
        public double[] velocities;

        public Ur5ToolMsg()
        {
            this.position = new double[3];
            this.rotation = new double[3];
            this.velocities = new double[6];
        }

        public Ur5ToolMsg(double[] position, double[] rotation, double[] velocities)
        {
            this.position = position;
            this.rotation = rotation;
            this.velocities = velocities;
        }

        public static Ur5ToolMsg Deserialize(MessageDeserializer deserializer) => new Ur5ToolMsg(deserializer);

        private Ur5ToolMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.position, sizeof(double), 3);
            deserializer.Read(out this.rotation, sizeof(double), 3);
            deserializer.Read(out this.velocities, sizeof(double), 6);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.position);
            serializer.Write(this.rotation);
            serializer.Write(this.velocities);
        }

        public override string ToString()
        {
            return "Ur5ToolMsg: " +
            "\nposition: " + System.String.Join(", ", position.ToList()) +
            "\nrotation: " + System.String.Join(", ", rotation.ToList()) +
            "\nvelocities: " + System.String.Join(", ", velocities.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
