//Do not edit! This file was generated by Unity-ROS MessageGeneration.

using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.IrlRobots
{
    [Serializable]
    public class Ur5ToolMsg : Message
    {
        public const string k_RosMessageName = "irl_robots/ur5Tool";
        public override string RosMessageName => k_RosMessageName;

        public double[] position;
        public double[] rotation;
        public double[] velocities;

        public Ur5ToolMsg()
        {
            position = new double[3];
            rotation = new double[3];
            velocities = new double[6];
        }

        public Ur5ToolMsg(double[] position, double[] rotation, double[] velocities)
        {
            this.position = position;
            this.rotation = rotation;
            this.velocities = velocities;
        }

        public static Ur5ToolMsg Deserialize(MessageDeserializer deserializer)
        {
            return new Ur5ToolMsg(deserializer);
        }

        private Ur5ToolMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out position, sizeof(double), 3);
            deserializer.Read(out rotation, sizeof(double), 3);
            deserializer.Read(out velocities, sizeof(double), 6);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(position);
            serializer.Write(rotation);
            serializer.Write(velocities);
        }

        public override string ToString()
        {
            return "Ur5ToolMsg: " +
                   "\nposition: " + string.Join(", ", position.ToList()) +
                   "\nrotation: " + string.Join(", ", rotation.ToList()) +
                   "\nvelocities: " + string.Join(", ", velocities.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}