//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RoboteqDiff
{
    [Serializable]
    public class EMORequest : Message
    {
        public const string k_RosMessageName = "roboteq_diff_msgs/EMO";
        public override string RosMessageName => k_RosMessageName;

        public bool activate_emo;

        public EMORequest()
        {
            this.activate_emo = false;
        }

        public EMORequest(bool activate_emo)
        {
            this.activate_emo = activate_emo;
        }

        public static EMORequest Deserialize(MessageDeserializer deserializer) => new EMORequest(deserializer);

        private EMORequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.activate_emo);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.activate_emo);
        }

        public override string ToString()
        {
            return "EMORequest: " +
            "\nactivate_emo: " + activate_emo.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
