//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RoboteqDiff
{
    [Serializable]
    public class RequestBrushActivateRequest : Message
    {
        public const string k_RosMessageName = "roboteq_diff_msgs/RequestBrushActivate";
        public override string RosMessageName => k_RosMessageName;

        public bool activate;

        public RequestBrushActivateRequest()
        {
            this.activate = false;
        }

        public RequestBrushActivateRequest(bool activate)
        {
            this.activate = activate;
        }

        public static RequestBrushActivateRequest Deserialize(MessageDeserializer deserializer) => new RequestBrushActivateRequest(deserializer);

        private RequestBrushActivateRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.activate);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.activate);
        }

        public override string ToString()
        {
            return "RequestBrushActivateRequest: " +
            "\nactivate: " + activate.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
