//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RoboteqDiff
{
    [Serializable]
    public class RequestChargeActivateResponse : Message
    {
        public const string k_RosMessageName = "roboteq_diff_msgs/RequestChargeActivate";
        public override string RosMessageName => k_RosMessageName;

        public bool complete;

        public RequestChargeActivateResponse()
        {
            this.complete = false;
        }

        public RequestChargeActivateResponse(bool complete)
        {
            this.complete = complete;
        }

        public static RequestChargeActivateResponse Deserialize(MessageDeserializer deserializer) => new RequestChargeActivateResponse(deserializer);

        private RequestChargeActivateResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.complete);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.complete);
        }

        public override string ToString()
        {
            return "RequestChargeActivateResponse: " +
            "\ncomplete: " + complete.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
