//Do not edit! This file was generated by Unity-ROS MessageGeneration.

using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RoboteqDiff
{
    [Serializable]
    public class RequestBrushSpeedRequest : Message
    {
        public const string k_RosMessageName = "roboteq_diff_msgs/RequestBrushSpeed";
        public override string RosMessageName => k_RosMessageName;

        public float brush_rpm_req;

        public RequestBrushSpeedRequest()
        {
            brush_rpm_req = 0.0f;
        }

        public RequestBrushSpeedRequest(float brush_rpm_req)
        {
            this.brush_rpm_req = brush_rpm_req;
        }

        public static RequestBrushSpeedRequest Deserialize(MessageDeserializer deserializer)
        {
            return new RequestBrushSpeedRequest(deserializer);
        }

        private RequestBrushSpeedRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out brush_rpm_req);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(brush_rpm_req);
        }

        public override string ToString()
        {
            return "RequestBrushSpeedRequest: " +
                   "\nbrush_rpm_req: " + brush_rpm_req.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}