//Do not edit! This file was generated by Unity-ROS MessageGeneration.

using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RoboteqDiff
{
    [Serializable]
    public class RequestBrushSpeedResponse : Message
    {
        public const string k_RosMessageName = "roboteq_diff_msgs/RequestBrushSpeed";
        public override string RosMessageName => k_RosMessageName;

        public float brush_rpm_res;

        public RequestBrushSpeedResponse()
        {
            brush_rpm_res = 0.0f;
        }

        public RequestBrushSpeedResponse(float brush_rpm_res)
        {
            this.brush_rpm_res = brush_rpm_res;
        }

        public static RequestBrushSpeedResponse Deserialize(MessageDeserializer deserializer)
        {
            return new RequestBrushSpeedResponse(deserializer);
        }

        private RequestBrushSpeedResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out brush_rpm_res);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(brush_rpm_res);
        }

        public override string ToString()
        {
            return "RequestBrushSpeedResponse: " +
                   "\nbrush_rpm_res: " + brush_rpm_res.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}