//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RoboteqDiff
{
    [Serializable]
    public class ToggleClosedLoopRequest : Message
    {
        public const string k_RosMessageName = "roboteq_diff_msgs/ToggleClosedLoop";
        public override string RosMessageName => k_RosMessageName;

        public bool closed_loop_req;

        public ToggleClosedLoopRequest()
        {
            this.closed_loop_req = false;
        }

        public ToggleClosedLoopRequest(bool closed_loop_req)
        {
            this.closed_loop_req = closed_loop_req;
        }

        public static ToggleClosedLoopRequest Deserialize(MessageDeserializer deserializer) => new ToggleClosedLoopRequest(deserializer);

        private ToggleClosedLoopRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.closed_loop_req);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.closed_loop_req);
        }

        public override string ToString()
        {
            return "ToggleClosedLoopRequest: " +
            "\nclosed_loop_req: " + closed_loop_req.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
