//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RoboteqDiff
{
    [Serializable]
    public class ToggleClosedLoopResponse : Message
    {
        public const string k_RosMessageName = "roboteq_diff_msgs/ToggleClosedLoop";
        public override string RosMessageName => k_RosMessageName;

        public bool success;

        public ToggleClosedLoopResponse()
        {
            this.success = false;
        }

        public ToggleClosedLoopResponse(bool success)
        {
            this.success = success;
        }

        public static ToggleClosedLoopResponse Deserialize(MessageDeserializer deserializer) => new ToggleClosedLoopResponse(deserializer);

        private ToggleClosedLoopResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "ToggleClosedLoopResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
